// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAssociationAPI.Data;

namespace StudentAssociationAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230104100147_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(85)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(85)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Name")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<string>("AssociationId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("MemberId")
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("MemberId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Association", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Associations");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.AssociationMembership", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("AssociationId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MemberId")
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("MemberId");

                    b.ToTable("AssociationMemberships");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.BoardMembership", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("AssociationId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MemberId")
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("MemberId");

                    b.ToTable("BoardMemberships");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Commitee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("AssociationId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InaugurationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.ToTable("Commitees");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.CommiteeMembership", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CommiteeId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MemberId")
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("CommiteeId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("CommiteeMemberships");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CommiteeId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CommiteeId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.EventRegistration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("EventId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("MemberId")
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("MemberId");

                    b.ToTable("EventRegistrations");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(85)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(85)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Application", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.Association", "Association")
                        .WithMany("Applications")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudentAssociationAPI.Entities.Member", "Member")
                        .WithMany("Applications")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Association");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.AssociationMembership", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.Association", "Association")
                        .WithMany("AssociationMemberships")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudentAssociationAPI.Entities.Member", "Member")
                        .WithMany("AssociationMemberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Association");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.BoardMembership", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.Association", "Association")
                        .WithMany("BoardMemberships")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudentAssociationAPI.Entities.Member", "Member")
                        .WithMany("BoardMemberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Association");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Commitee", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.Association", "Association")
                        .WithMany("Commitees")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Association");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.CommiteeMembership", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.Commitee", "Commitee")
                        .WithMany("CommiteeMemberships")
                        .HasForeignKey("CommiteeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudentAssociationAPI.Entities.Member", "Member")
                        .WithOne("CommiteeMembership")
                        .HasForeignKey("StudentAssociationAPI.Entities.CommiteeMembership", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Commitee");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Event", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.Commitee", "Commitee")
                        .WithMany("Events")
                        .HasForeignKey("CommiteeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Commitee");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.EventRegistration", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.Event", "Event")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudentAssociationAPI.Entities.Member", "Member")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Event");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Member", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("StudentAssociationAPI.Entities.Member", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.UserRole", b =>
                {
                    b.HasOne("StudentAssociationAPI.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentAssociationAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Association", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("AssociationMemberships");

                    b.Navigation("BoardMemberships");

                    b.Navigation("Commitees");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Commitee", b =>
                {
                    b.Navigation("CommiteeMemberships");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Event", b =>
                {
                    b.Navigation("EventRegistrations");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.Member", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("AssociationMemberships");

                    b.Navigation("BoardMemberships");

                    b.Navigation("CommiteeMembership");

                    b.Navigation("EventRegistrations");
                });

            modelBuilder.Entity("StudentAssociationAPI.Entities.User", b =>
                {
                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
